# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(832, 520)
        Form.setMouseTracking(True)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: #28292c;")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(810, 0, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #1f1f22\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 34, 63);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 34, 63);\n"
"    background-color:  #1f1f22\n"
"}")
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.minimize = QtWidgets.QPushButton(Form)
        self.minimize.setGeometry(QtCore.QRect(790, 0, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.minimize.setFont(font)
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #1f1f22\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(134, 134, 134);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"}")
        self.minimize.setCheckable(False)
        self.minimize.setChecked(False)
        self.minimize.setAutoRepeat(False)
        self.minimize.setAutoExclusive(False)
        self.minimize.setAutoDefault(False)
        self.minimize.setDefault(False)
        self.minimize.setFlat(True)
        self.minimize.setObjectName("minimize")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 20, 241, 501))
        self.frame.setStyleSheet("background-color: #1f1f22")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(149, 149, 149)")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 110, 191, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    margin-right: auto;\n"
"    color: rgb(149, 149, 149)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(212, 212, 212)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-right: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(2, 142, 199, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    margin-right: auto;\n"
"    color: rgb(149, 149, 149)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(212, 212, 212)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-right: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(-26, 172, 211, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    margin-right: auto;\n"
"    color: rgb(149, 149, 149)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(212, 212, 212)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-right: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(-18, 200, 199, 39))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    margin-right: auto;\n"
"    color: rgb(149, 149, 149)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(212, 212, 212)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-right: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    border: none;\n"
"    outline:none;\n"
"    padding: 5px;\n"
"    margin-left: auto;\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setChecked(False)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 841, 21))
        self.frame_2.setStyleSheet("background-color: #1f1f22")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.minimize.raise_()
        self.pushButton.raise_()
        self.frame.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton, self.minimize)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "X"))
        self.minimize.setText(_translate("Form", "-"))
        self.label.setText(_translate("Form", "Тест"))
        self.pushButton_2.setText(_translate("Form", "Консоль"))
        self.pushButton_3.setText(_translate("Form", "Настроки"))
        self.pushButton_4.setText(_translate("Form", "Моды"))
        self.pushButton_5.setText(_translate("Form", "Донат"))
